name: xls-to-xlsx

# Controls when the action will run. 
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
    - main

jobs:
  build:
    runs-on:  windows-2019


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: pwd
        run:
          pwd
           
      #- name: Install Office
      #  run: choco install office365business
